% regole generate con 25 esempi positivi, 25 negativi, presi in modo casuale e MAXITER = 3
high_vote_average(A) :- film(B,"drama",A,C,D,E,F,G,H,I,J), film(K,L,A,M,N,"",O,P,Q,R,S)
high_vote_average(A) :- ruolo(A,B,"himself"), attore(C,B,2)
high_vote_average(A) :- film(B,"documentary",A,C,D,E,F,G,H,I,J), film(K,L,A,M,N,"",O,P,Q,R,S)
high_vote_average(A) :- ruolo_crew(A,B,"sound"), film(C,"drama",A,D,E,F,G,H,I,J,K)
high_vote_average(A) :- film(B,"music",A,C,D,E,F,G,H,I,J)
high_vote_average(A) :- film(B,"western",A,C,D,E,F,G,H,I,J)
high_vote_average(A) :- film(B,"history",A,C,D,E,F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,"ja",D,E,F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,"hi",D,E,F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,"tr",D,E,F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,"pl",D,E,F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,"mk",D,E,F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,D,E,"amblin television",F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,D,E,"monogram pictures",F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,D,E,"columbia pictures corporation",F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,D,E,"full moon entertainment",F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,D,E,"metro-goldwyn-mayer mgm",F,G,H,I,J)

% regole generate con 25 esempi positivi, 25 negativi, presi in modo casuale e MAXITER = 4
high_vote_average(A) :- film(B,"drama",A,C,D,E,F,G,H,I,J), film(K,L,A,M,N,"",O,P,Q,R,S)
high_vote_average(A) :- ruolo(A,B,"himself"), attore(C,B,2)
high_vote_average(A) :- film(B,"documentary",A,C,D,E,F,G,H,I,J), film(K,L,A,M,N,"",O,P,Q,R,S)
high_vote_average(A) :- ruolo_crew(A,B,"sound"), film(C,"drama",A,D,E,F,G,H,I,J,K)
high_vote_average(A) :- film(B,"",A,C,D,E,F,G,H,I,J), ruolo_crew(A,K,"writer"), \+membro_crew(K,"jack kerouac",0)
high_vote_average(A) :- film(B,"music",A,C,D,E,F,G,H,I,J)
high_vote_average(A) :- film(B,"history",A,C,D,E,F,G,H,I,J)
high_vote_average(A) :- film(B,"western",A,C,D,E,F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,"mk",D,E,F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,"tr",D,E,F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,"pl",D,E,F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,D,E,"full moon entertainment",F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,D,E,"monogram pictures",F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,D,E,"metro-goldwyn-mayer mgm",F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,D,E,"columbia pictures corporation",F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,D,E,"amblin television",F,G,H,I,J)

%regole generate con 50 esempi positivi, 50 negativi, presi in modo casuale e MAXITER = 4
high_vote_average(A) :- film(B,"documentary",A,C,D,E,F,G,H,I,J)
high_vote_average(A) :- ruolo(A,B,"himself")
high_vote_average(A) :- ruolo_crew(A,B,"novel"), film(C,D,A,E,F,"",G,H,I,J,K)
high_vote_average(A) :- ruolo(A,B,""), film(C,D,A,"en",E,F,G,H,I,J,K), attore(L,B,0)
high_vote_average(A) :- film(B,"",A,C,D,E,F,G,H,I,J), ruolo(A,K,L), attore(M,K,2)
high_vote_average(A) :- film(B,C,A,"pt",D,E,F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,"de",D,E,F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,D,E,"metro-goldwyn-mayer mgm",F,G,H,I,J)
high_vote_average(A) :- film(B,"thriller",A,C,D,E,F,G,H,I,J), film(K,L,A,M,N,"",O,P,Q,R,S)
high_vote_average(A) :- film(B,"foreign",A,C,D,E,F,G,H,I,J)
high_vote_average(A) :- film(B,"science fiction",A,C,D,E,F,G,H,I,J)
high_vote_average(A) :- film(B,"music",A,C,D,E,F,G,H,I,J)
high_vote_average(A) :- film(B,"war",A,C,D,E,F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,"mk",D,E,F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,"tr",D,E,F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,D,E,"monogram pictures",F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,D,E,"herman cohen productions",F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,D,E,"production ig",F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,D,E,"ciné cinq",F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,D,E,"beard collins shores productions",F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,D,E,"full moon entertainment",F,G,H,I,J)
high_vote_average(A) :- film(B,C,A,D,E,"svenska filminstitutet",F,G,H,I,J)
high_vote_average(A) :- ruolo(A,B,"hector")
